name = "grille_pain"
target = "javascript"
version = "1.1.0"

gleam = ">= 1.8.0"

description = "Toaster, made in lustre, for gleam"
internal_modules = ["grille_pain/internals", "grille_pain/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "grille-pain"}

[dependencies]
birl = ">= 1.8.0 and < 2.0.0"
gleam_stdlib = ">= 0.54.0 and < 1.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
sketch = ">= 4.0.0 and < 5.0.0"
sketch_lustre = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
