name = "grille_pain"
target = "javascript"
version = "1.1.2"

gleam = ">= 1.9.0"

description = "Toaster, made in lustre, for gleam"
internal_modules = ["grille_pain/internals", "grille_pain/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "grille-pain"}

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 1.0.0"
lustre = ">= 4.5.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
