name = "grille_pain"
target = "javascript"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

description = "Time traveller debugger, tailor-made for Lustre"
internal_modules = ["grille_pain/internals", "grille_pain/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "grille_pain"}

[dependencies]
birl = ">= 1.6.1 and < 2.0.0"
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
lustre = ">= 4.1.8 and < 5.0.0"
plinth = ">= 0.2.0 and < 1.0.0"
sketch = ">= 2.0.0 and < 3.0.0"
tardis = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
