name: Deploy demo

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Downloading dependencies
        run: gleam deps download
        working-directory: e2e/demo
      - name: Build demo
        run: gleam run -m lustre/dev build
        working-directory: e2e/demo
      - name: Upload artifacts
        uses: actions/upload-artifacts@v4
        working-directory: e2e/demo
        with:
          name: github-pages
          path: |
            priv
            index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
