name: Deploy demo

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
        working-directory: e2e/demo
      - run: gleam run -m lustre/dev build
        working-directory: e2e/demo
      - uses: actions/upload-artifacts@v4
        working-directory: e2e/demo
        with:
          name: github-pages
          path: |
            priv
            index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
